COGENT_DB = /home/teege/cogent/cogent/.cabal-sandbox/x86_64-linux-ghc-8.4.3-packages.conf.d/
GENCOT_SRC = ../..
EXPOSEPACKS = -package language-c

Decls: Decls.hs
	ghc $(EXPOSEPACKS) -i$(GENCOT_SRC) --make -O $@.hs


