COGENT_DB = /home/teege/cogent/cogent/.cabal-sandbox/x86_64-linux-ghc-8.4.3-packages.conf.d/

Origin: Origin.hs
	ghc -package-db $(COGENT_DB) --make -O $@.hs

Names: Names.hs
	ghc -package-db $(COGENT_DB) --make -O $@.hs

Input: Input.hs
	ghc -package-db $(COGENT_DB) --make -O $@.hs

